### ISSUE TITLE
Create the Team and Individual Card components for the About page

### ISSUE THREAD

**Issue by syncopascual** [up-csi/up-csi.github.io#36]
Reassigning to @KindaExists!

Grouped these two together since the development for both is pretty intertwined! 

The larger Team component at the bottom of the About page contains buttons to navigate between the different committees (default for the page is the executive committee). The Individual Card component contains the info of each member (details can also be found more sa Figma file, like the colors for the dark mode versions of each component etc.).

The content itself will come from PRs from the members themselves, so that can be placeholder for now!

**Comment by ehrelevant** [comment]
Completed in #58, although we should also implement the proposed changes discussed in #63.
