### ISSUE TITLE
Create Events page skeleton and Events page Hero

### ISSUE THREAD

**Issue by syncopascual** [up-csi/up-csi.github.io#55]
Part of issue #25! For the Events page, we have to make a page that showcases the org's past events. The B&C Drive contains images for a few past events [here](https://drive.google.com/drive/folders/1RFpQRa-rLEOsUbIkLwkWOr6mUP-JPavM), so you can check the folder for images to use.

We'll be implementing the following components as shown in [this mockup](https://www.figma.com/file/gdObjB04j7BT36Q0lQ9GzL/UP-CSI-Website?type=design&node-id=203%3A16&mode=design&t=JuSvrpPccS4B64M0-1)!
- [x] @rue-22 Hero component at the top that shows the **next upcoming CSI event**. Maybe for now we can put the last event here as a placeholder (which would I think be EX Series?). 
- [x] @KindaExists Card components containing past and upcoming event details. The "More Info" button can remain functionless for now until we decide how the info will be displayed.
- [x] @KindaExists Tab bar below the Hero component that filters the cards based on which tab was clicked (ex. if the EX Series tab is clicked, only iterations of the EX Series will show).

Make sure to also use the styles/designs of the components we were using in v1!

**Comment by ehrelevant** [comment]
I'd say we can consider this issue completed after PRs #61 and #63 are resolved:
- #61 - The component still needs to be added to the page with some (placeholder) content. 
- #63 - The event content to a separate `.js` file and it should be good to go.

**Comment by VeeIsForVanana** [comment]
TODO: Remove PR #61 in favor of a PR to be done from @ehrelevant 's fork to resolve this.
