### ISSUE TITLE
Create a custom 404 page

### ISSUE THREAD

**Issue by syncopascual** [up-csi/up-csi.github.io#59]
Assigned to @galierie!

Define a fallback that goes to +error.svelte. The code for this is in the SvelteKit docs under Errors and Redirects! In terms of layout, we can use other basic 404 pages as references.

**Comment by Anjellyrika** [comment]
Hello! Here's a Lino doodle that could be used for the 404 image. Let me know if you need a different size or file format; this was all I could find from the CSI drive for now 😄

![thonk_lino](https://github.com/up-csi/up-csi.github.io/assets/98273014/b6344418-1ae8-4c1a-9488-0b7911a55901)

**Comment by ehrelevant** [comment]
Completed in #60 and #64
