### ISSUE TITLE
Generalize EventsPanel Component

### ISSUE THREAD

**Issue by VeeIsForVanana** [up-csi/up-csi.github.io#73]
Combine functionality for EventsPanel Components

**Comment by ehrelevant** [comment]
@syncopascual — As you may have noticed, the Events and Projects pages use `EventsPanel` and `EventCard`. That said, these “Event” components aren’t particularly compatible with the Projects page. If anything, they are a placeholder measure. We should look into generalizing the pagination and tag functions in `EventPanel` in anticipation of when we start adding project details onto the page.
- It is up to you to decide on the approach for this one. You may also choose to forgo generalization entirely and split the component into two for the Events and Projects pages if you deem this a better choice for the future, but you'll likely need to convice the reviewers for this one.
- If you can incorporate the enums mentioned in #69 (via type unions maybe?), that would be appreciated.
